CREATE DATABASE feedback_db;
USE feedback_db;

CREATE TABLE feedbacks ( 
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
message TEXT NOT NULL,
rating INT CHECK (rating BETWEEN 1 AND 5),
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
